### ISSUE TITLE
No longer working with Macos 15

### ISSUE THREAD

**Issue by HiimHyy** [rurza/BatFi#55]
I have recently updated my mac to sequoia, the app stopped working and no longer pause at 80%, It asked me to perform Onboarding every time i reopen it.

**Comment by plyght** [comment]
same issue here; also stuck on initializing mode on sequoia.

**Comment by Eirperuier** [comment]
same here

**Comment by plyght** [comment]
@rurza any updates?

**Comment by rurza** [comment]
Thanks for reporting the problem. 
I won’t bother spending time testing it on macOS 15.0 until beta 3.

**Comment by rurza** [comment]
I've double checked – there is no changes in APIs I'm using, which means it's a bug on macOS. I'll schedule a call with Apple to discuss it.

**Comment by Xytronix** [comment]
<img width="260" alt="image" src="https://github.com/rurza/BatFi/assets/32957125/84f7ecbb-cf7a-447b-802a-0f7dd3047494">
<img width="310" alt="image" src="https://github.com/rurza/BatFi/assets/32957125/0684d128-1b1c-41aa-af92-00ba3a6a0d8e">

**Comment by rurza** [comment]
@Xytronix @plyght 
Can you send me a screenshot from the System Settings -> Login Items?

**Comment by plyght** [comment]
> @Xytronix @plyght Can you send me a screenshot from the System Settings -> Login Items?

I think part of the issue is that Sequoia keeps removing the "allow in background" thing you have to enable during the setup of BatFi. 
[Screenshot](https://github.com/rurza/BatFi/assets/81438024/22697599-9f7c-4d70-8d7e-309f343bade5) 
BatFi allow in background should be [here](https://github.com/rurza/BatFi/assets/81438024/4056e45b-e05d-41fe-a915-7147c09e9f5f)

**Comment by plyght** [comment]
> I've double checked – there is no changes in APIs I'm using, which means it's a bug on macOS. I'll schedule a call with Apple to discuss it.

@rurza Any updates on the call w/ Apple?

**Comment by mcernohorsky** [comment]
thanks for looking into this

**Comment by rurza** [comment]
Hey!

We should wait for the next beta. The engineer I spoke with was well-prepared and aware of some issues in the current seed.

But...

Did you install the macOS beta on a separate volume? I did, and I experienced the same issues you mentioned. However, the app suddenly started working. To be honest, I don't know how I resolved it. Initially, I thought it was due to some changes I made in the XPC connection, but that wasn’t the case because the existing version of the app works as well. My guess is that it started working because I deleted the other copy of the app that was on the separate volume. Maybe this will work for you?

**Comment by plyght** [comment]
> Hey!
> 
> 
> 
> We should wait for the next beta. The engineer I spoke with was well-prepared and aware of some issues in the current seed.
> 
> 
> 
> But...
> 
> 
> 
> Did you install the macOS beta on a separate volume? I did, and I experienced the same issues you mentioned. However, the app suddenly started working. To be honest, I don't know how I resolved it. Initially, I thought it was due to some changes I made in the XPC connection, but that wasn’t the case because the existing version of the app works as well. My guess is that it started working because I deleted the other copy of the app that was on the separate volume. Maybe this will work for you?

@rurza That seems odd to me as the External volume shouldn't have access to the other, and shouldn't change anything (as far as I know). I did not install Sequoia onto a separate volume, so I cannot attempt the fix you described.

**Comment by rurza** [comment]
Actually, it's completely normal and expected behavior that an OS has access to other mounted volumes (for example, to index them). It's definitely not a trivial topic to determine what the system should do in some edge cases. Unfortunately, apps like BatFi are at a disadvantage. From Apple's perspective (and the best proof is the direction they chose for their newer platforms), the user shouldn't have to give admin permission to some third-party app in the first place. But here we are :)

Anyway, I've released a new beta. I highly recommend it. It should fix all the issues I know of from the release 2.0.0, and it works on my machine :D

**Comment by plyght** [comment]
> Actually, it's completely normal and expected behavior that an OS has access to other mounted volumes (for example, to index them). It's definitely not a trivial topic to determine what the system should do in some edge cases. Unfortunately, apps like BatFi are at a disadvantage. From Apple's perspective (and the best proof is the direction they chose for their newer platforms), the user shouldn't have to give admin permission to some third-party app in the first place. But here we are :)
> 
> 
> 
> Anyway, I've released a new beta. I highly recommend it. It should fix all the issues I know of from the release 2.0.0, and it works on my machine :D

@rurza Weird! you learn something new everyday. 
I'll try out that new beta when I get home. Thanks for being responsive and helpful.

**Comment by plyght** [comment]
> Actually, it's completely normal and expected behavior that an OS has access to other mounted volumes (for example, to index them). It's definitely not a trivial topic to determine what the system should do in some edge cases. Unfortunately, apps like BatFi are at a disadvantage. From Apple's perspective (and the best proof is the direction they chose for their newer platforms), the user shouldn't have to give admin permission to some third-party app in the first place. But here we are :)
> 
> Anyway, I've released a new beta. I highly recommend it. It should fix all the issues I know of from the release 2.0.0, and it works on my machine :D

@rurza BatFi 2.0.1 Beta did not fix the issue on my machine.

**Comment by plyght** [comment]
> > Actually, it's completely normal and expected behavior that an OS has access to other mounted volumes (for example, to index them). It's definitely not a trivial topic to determine what the system should do in some edge cases. Unfortunately, apps like BatFi are at a disadvantage. From Apple's perspective (and the best proof is the direction they chose for their newer platforms), the user shouldn't have to give admin permission to some third-party app in the first place. But here we are :)
> 
> > 
> 
> > Anyway, I've released a new beta. I highly recommend it. It should fix all the issues I know of from the release 2.0.0, and it works on my machine :D
> 
> 
> 
> @rurza BatFi 2.0.1 Beta did not fix the issue on my machine.

@rurza just following up on this to check for any updates.

**Comment by rurza** [comment]
@plyght 
> We should wait for the next beta.

**Comment by plyght** [comment]
> @plyght 
> 
> > We should wait for the next beta.

I see. wait for the next MacOS beta. Makes sense! Thanks for reminding me.

**Comment by plyght** [comment]
> Hi guys! By any chance did you find a way to fix it on Sequoia _Version 15.0 Beta (24A5264n)_? 
> 
> 
> 
> upd: I have beta 2.0.1 of BatFi
> 
> upd: IC that we need to wait till new beta comes out, just was curious maybe there is a workaround)

@cinestl as of now, no one (to my knowledge) has a workaround.

**Comment by ThatGuyWhomAsked** [comment]
I got it to work - I am using the 1st DB and I clicked DENY on the prompt (Bat-fi added items that can run in the bg) , and then allowed inside of system settings separately , it works like a charm for me now

**Comment by cinestl** [comment]
> I got it to work - I am using the 1st DB and I clicked DENY on the prompt (Bat-fi added items that can run in the bg) , and then allowed inside of system settings separately , it works like a charm for me now. @plyght @rurza

Did you uninstall the app or just closed and launched?

**Comment by rurza** [comment]
Exactly, that’s the core of the issue: the daemon responsible for matching the app with the helper has a bug. I am experiencing the same issue that @cinestl described. The helper is displayed instead of the app and is marked as “from an unidentified developer.” If @cinestl quits System Settings and then opens Login Items again, the “garbage collection” mechanism deletes this entry.

This workaround worked for me for a while, but then it stopped. I have restarted the OS and used `sfltool resetbtm` numerous times, to the point where I’m unsure what, if anything, actually helped. As of now, I still have no solution.

**Comment by ThatGuyWhomAsked** [comment]
> > I got it to work - I am using the 1st DB and I clicked DENY on the prompt (Bat-fi added items that can run in the bg) , and then allowed inside of system settings separately , it works like a charm for me now. @plyght @rurza
> 
> Did you uninstall the app or just closed and launched? <img alt="image" width="470" src="https://private-user-images.githubusercontent.com/132860138/341054456-941e996e-601d-42db-b9c1-85c07888cb12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NzExODMsIm5iZiI6MTcxODk3MDg4MywicGF0aCI6Ii8xMzI4NjAxMzgvMzQxMDU0NDU2LTk0MWU5OTZlLTYwMWQtNDJkYi1iOWMxLTg1YzA3ODg4Y2IxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQxMTU0NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NWRkOWJhNTYxM2RhNTk3YTE0OWM2NGQ1NjljNDI5MmQxZGNjMTE3MWM3NGU3Njc0Nzk4OWE0M2M3ZGRmNDA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VXxHJIEOyJtYE_c1cVSgS8eF5RSh_yRn4YXRxhDHBYg">
> 
> Cuz I just have this thing that does nothing for me =(

Can you just turn it on?

**Comment by cinestl** [comment]
> > > I got it to work - I am using the 1st DB and I clicked DENY on the prompt (Bat-fi added items that can run in the bg) , and then allowed inside of system settings separately , it works like a charm for me now. @plyght @rurza
> > 
> > 
> > Did you uninstall the app or just closed and launched? <img alt="image" width="470" src="https://private-user-images.githubusercontent.com/132860138/341054456-941e996e-601d-42db-b9c1-85c07888cb12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NzExODMsIm5iZiI6MTcxODk3MDg4MywicGF0aCI6Ii8xMzI4NjAxMzgvMzQxMDU0NDU2LTk0MWU5OTZlLTYwMWQtNDJkYi1iOWMxLTg1YzA3ODg4Y2IxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQxMTU0NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NWRkOWJhNTYxM2RhNTk3YTE0OWM2NGQ1NjljNDI5MmQxZGNjMTE3MWM3NGU3Njc0Nzk4OWE0M2M3ZGRmNDA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VXxHJIEOyJtYE_c1cVSgS8eF5RSh_yRn4YXRxhDHBYg">
> > Cuz I just have this thing that does nothing for me =(
> 
> Can't you just turn it on?

Yeah, I've enabled it, and after I close Settings, it disappears as @rurza mentioned before, so no luck here

**Comment by GavinMcNabb** [comment]
I can confim that this has been resolved in Beta 2. You do have to go through the onboarding one time but it'll stick on reboot.
![batfi-beta2](https://github.com/rurza/BatFi/assets/48451352/2f279c91-5e88-45e2-bd41-596ddf08b899)

**Comment by cinestl** [comment]
<img width="302" alt="image" src="https://github.com/rurza/BatFi/assets/132860138/acc06d85-37c9-4543-aa82-c75e1475382a">
<img width="474" alt="image" src="https://github.com/rurza/BatFi/assets/132860138/aeb84f5a-5c18-43ee-a9f4-b7b8b60ed1f1">

Yeah MacOS Beta 2 rules! You just need to manually enable thing in Login items and reboot your mac, tho I'm using beta update of BatFi)

**Comment by Xytronix** [comment]
indeed fixed it #close
